# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/emdtool',
                'doc_host': 'https://NaveenDeepak.github.io',
                'git_url': 'https://github.com/NaveenDeepak/emdtool',
                'lib_path': 'emdtool'},
  'syms': {'emdtool.core': {'emdtool.core.foo': ('core.html#foo', 'emdtool/core.py')}}}